## Code for Linear Regression and Decision Tree

In [59]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from datetime import timezone, datetime
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder
#from sklearn.compose import ColumnTransformer 
import datetime as dt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold 
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import classification_report, confusion_matrix

### Importing Dataset
hingek10.csv and hingek20.csv are the training results of the low rank model of clustering the patients' information. Diabetes_Numerical.csv is the dataset used for training linear regression and decision tree models.

In [73]:
hinge10 = pd.read_csv('../data/hingek10.csv')
#hinge20 = pd.read_csv('../data/hingek20.csv')
origin20 = pd.read_csv('../data/GLRMk20.csv')
origin5 = pd.read_csv('../data/GLRMk5.csv')
df_pat = pd.read_csv('../data/Diabetes_Numerical.csv')

hinge7 = pd.read_csv('../data/hingek7.csv')
param7 = pd.read_csv('../data/hingeparam7.csv')
hinge6 = pd.read_csv('../data/hingek6.csv')
param6 = pd.read_csv('../data/hingeparam6.csv')

param100_7=pd.read_csv('../data/hingeparam100.7.csv')

In [61]:
hinge7

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x10301,x10302,x10303,x10304,x10305,x10306,x10307,x10308,x10309,x10310
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [62]:
param7

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x10301,x10302,x10303,x10304,x10305,x10306,x10307,x10308,x10309,x10310
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
df_pat.head()

,SUBJECT_ID,LOS,HOSPITALIZATION,ORDINAL_AGE,ELECTIVE,EMERGENCY,NEWBORN,URGENT,Government,Medicaid,...,NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER,HISPANIC/LATINO - CENTRAL AMERICAN (OTHER),ASIAN - JAPANESE,ASIAN - THAI,HISPANIC/LATINO - HONDURAN,HISPANIC/LATINO - CUBAN,MIDDLE EASTERN,ASIAN - OTHER,HISPANIC/LATINO - MEXICAN,AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE
0,13,3.6660,1,4,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,18,1.2885,1,6,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20,1.0508,1,8,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,21,14.2664,2,9,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,24,0.5124,1,4,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
df_pat['LOS']

0         3.6660
1         1.2885
2         1.0508
3        14.2664
4         0.5124
          ...
10305     5.6719
10306     2.8684
10307     3.1426
10308     2.1615
10309     1.1242
Name: LOS, Length: 10310, dtype: float64

## Function for regression training

In [65]:
def train_LR(X_train, X_test, y_train, y_test, i):
    # create training and testing vars
    #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
    print(X_train.shape, y_train.shape)
    print(X_test.shape, y_test.shape)
    lm = LinearRegression()
    model = lm.fit(X_train, y_train)
    y_pred = lm.predict(X_test)
    print("Score:", MSE(y_pred, y_test), '\n')
    #print(confusion_matrix(y_test, y_pred))
    #print(classification_report(y_test, y_pred))

In [66]:
def train_DT(X_train, X_test, y_train, y_test, i):
    # create training and testing vars
    print(X_train.shape, y_train.shape)
    print(X_test.shape, y_test.shape)
    dt = DecisionTreeRegressor()
    model = dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)
    print("Score:", MSE(y_pred, y_test), '\n')
    #print(confusion_matrix(y_test, y_pred))
    #print(classification_report(y_test, y_pred))

In [67]:
def trainModel(df_clus, df_pat, size):
    df_clus = df_clus.transpose()
    
    # get the clusters
    clusters = []
    for i in range(size):
        this_cluster = df_clus[df_clus[i] == 1]
        clusters.append(this_cluster)
    
    # get the index
    cluster = []
    for i in range(size):
        this_cluster = list(map(lambda x: int(x[1:]) - 1, list(clusters[i].index)))
        cluster.append(this_cluster)
        
    # split the patient dataframe
    pat_clustered = []
    for i in range(size):
        this_clu = df_pat[df_pat.index.isin(cluster[i])]
        pat_clustered.append(this_clu)
    for i in range(size):
        this_c = pat_clustered[i]
        if (len(this_c) > 0):
            this_df = this_c.iloc[:, 1:]
            y = this_df.LOS
            X = this_df.iloc[:, 1:]
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
            print('\n Cluster '+ str(i+1)+ ': \n')
            print('Linear Regression: ')
            train_LR(X_train, X_test, y_train, y_test, i)
            print('Decission Tree: ')
            train_DT(X_train, X_test, y_train, y_test, i)
        else:
            print('Cluster'+ str(i+1)+ ' is empty. \n')

In [68]:

def printcluster(df_clus, df_pat, size):
    df_clus = df_clus.transpose()
    
    # get the clusters
    clusters = []
    for i in range(size):
        this_cluster = df_clus[df_clus[i] == 1]
        clusters.append(this_cluster)
    print(clusters)
    # get the index
    cluster = []
    for i in range(size):
        this_cluster = list(map(lambda x: int(x[1:]) - 1, list(clusters[i].index)))
        cluster.append(this_cluster)
        
    # split the patient dataframe
    pat_clustered = []
    for i in range(size):
        this_clu = df_pat[df_pat.index.isin(cluster[i])]
        pat_clustered.append(this_clu)
    for i in range(size):
        this_c = pat_clustered[i]
        if (len(this_c) > 0):
            this_df = this_c.iloc[:, 1:]
            y = this_df.LOS
            X = this_df.iloc[:, 1:]
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
            print('\n Cluster '+ str(i+1)+ ': \n')
            print('Linear Regression: ')
            train_LR(X_train, X_test, y_train, y_test, i)
            print('Decission Tree: ')
            train_DT(X_train, X_test, y_train, y_test, i)
        else:
            print('Cluster'+ str(i+1)+ ' is empty. \n')

In [69]:
printcluster(param7, df_pat, 7)

[          0    1    2    3    4    5    6
x2      1.0  0.0  0.0  0.0  0.0  0.0  0.0
x7      1.0  0.0  0.0  0.0  0.0  0.0  0.0
x18     1.0  0.0  0.0  0.0  0.0  0.0  0.0
x25     1.0  0.0  0.0  0.0  0.0  0.0  0.0
x28     1.0  0.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10278  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10289  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10299  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10306  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10308  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[1457 rows x 7 columns],           0    1    2    3    4    5    6
x3      0.0  1.0  0.0  0.0  0.0  0.0  0.0
x5      0.0  1.0  0.0  0.0  0.0  0.0  0.0
x6      0.0  1.0  0.0  0.0  0.0  0.0  0.0
x11     0.0  1.0  0.0  0.0  0.0  0.0  0.0
x22     0.0  1.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10295  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10296  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10297  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10298  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10300  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[1515 rows x 7 columns],           0    1    2    3    4    5    6
x10     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x14     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x16     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x19     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x26     0.0  0.0  1.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10246  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10258  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10269  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10279  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10288  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[1428 rows x 7 columns],           0    1    2    3    4    5    6
x1      0.0  0.0  0.0  1.0  0.0  0.0  0.0
x4      0.0  0.0  0.0  1.0  0.0  0.0  0.0
x9      0.0  0.0  0.0  1.0  0.0  0.0  0.0
x13     0.0  0.0  0.0  1.0  0.0  0.0  0.0
x17     0.0  0.0  0.0  1.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10293  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10303  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10307  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10309  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10310  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[1461 rows x 7 columns],           0    1    2    3    4    5    6
x8      0.0  0.0  0.0  0.0  1.0  0.0  0.0
x12     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x15     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x21     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x29     0.0  0.0  0.0  0.0  1.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10282  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10284  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10290  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10291  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10305  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[1509 rows x 7 columns],           0    1    2    3    4    5    6
x20     0.0  0.0  0.0  0.0  0.0  1.0  0.0
x31     0.0  0.0  0.0  0.0  0.0  1.0  0.0
x32     0.0  0.0  0.0  0.0  0.0  1.0  0.0
x48     0.0  0.0  0.0  0.0  0.0  1.0  0.0
x50     0.0  0.0  0.0  0.0  0.0  1.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10275  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10283  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10294  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10302  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10304  0.0  0.0  0.0  0.0  0.0  1.0  0.0

[1463 rows x 7 columns],           0    1    2    3    4    5    6
x23     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x27     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x34     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x41     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x44     0.0  0.0  0.0  0.0  0.0  0.0  1.0
...     ...  ...  ...  ...  ...  ...  ...
x10281  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10286  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10287  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10292  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10301  0.0  0.0  0.0  0.0  0.0  0.0  1.0

[1477 rows x 7 columns]]

 Cluster 1:

Linear Regression:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 8.529432375339422e+22

Decission Tree:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 89.88333794164383


 Cluster 2:

Linear Regression:
(1136, 919) (1136,)
(379, 919) (379,)
Score: 1.836602444490869e+23

Decission Tree:
(1136, 919) (1136,)
(379, 919) (379,)
Score: 73.74438183459104


 Cluster 3:

Linear Regression:
(1071, 919) (1071,)
(357, 919) (357,)
Score: 2.2151717354999782e+20

Decission Tree:
(1071, 919) (1071,)
(357, 919) (357,)
Score: 93.85439090313726


 Cluster 4:

Linear Regression:
(1095, 919) (1095,)
(366, 919) (366,)
Score: 2.8100741245389813e+22

Decission Tree:
(1095, 919) (1095,)
(366, 919) (366,)
Score: 142.23867690560792


 Cluster 5:

Linear Regression:
(1131, 919) (1131,)
(378, 919) (378,)
Score: 1.71832259120847e+23

Decission Tree:
(1131, 919) (1131,)
(378, 919) (378,)
Score: 93.1677735327778


 Cluster 6:

Linear Regression:
(1097, 919) (1097,)
(366, 919) (366,)
Score: 5.3098431224914945e+22

Decission Tree:
(1097, 919) (1097,)
(366, 919) (366,)
Score: 147.1200720721858


 Cluster 7:

Linear Regression:
(1107, 919) (1107,)
(370, 919) (370,)
Score: 2.3918732405968365e+21

Decission Tree:
(1107, 919) (1107,)
(370, 919) (370,)
Score: 62.65114372229729

In [70]:
printcluster(hinge7, df_pat, 7)

[          0    1    2    3    4    5    6
x1      1.0  0.0  0.0  0.0  0.0  0.0  0.0
x12     1.0  0.0  0.0  0.0  0.0  0.0  0.0
x31     1.0  0.0  0.0  0.0  0.0  0.0  0.0
x40     1.0  0.0  0.0  0.0  0.0  0.0  0.0
x41     1.0  0.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10259  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10261  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10269  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10285  1.0  0.0  0.0  0.0  0.0  0.0  0.0
x10306  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[1527 rows x 7 columns],           0    1    2    3    4    5    6
x8      0.0  1.0  0.0  0.0  0.0  0.0  0.0
x11     0.0  1.0  0.0  0.0  0.0  0.0  0.0
x19     0.0  1.0  0.0  0.0  0.0  0.0  0.0
x29     0.0  1.0  0.0  0.0  0.0  0.0  0.0
x34     0.0  1.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10290  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10294  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10297  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10300  0.0  1.0  0.0  0.0  0.0  0.0  0.0
x10301  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[1331 rows x 7 columns],           0    1    2    3    4    5    6
x5      0.0  0.0  1.0  0.0  0.0  0.0  0.0
x16     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x20     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x21     0.0  0.0  1.0  0.0  0.0  0.0  0.0
x28     0.0  0.0  1.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10241  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10270  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10271  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10272  0.0  0.0  1.0  0.0  0.0  0.0  0.0
x10275  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[1352 rows x 7 columns],           0    1    2    3    4    5    6
x9      0.0  0.0  0.0  1.0  0.0  0.0  0.0
x14     0.0  0.0  0.0  1.0  0.0  0.0  0.0
x25     0.0  0.0  0.0  1.0  0.0  0.0  0.0
x26     0.0  0.0  0.0  1.0  0.0  0.0  0.0
x27     0.0  0.0  0.0  1.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10293  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10296  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10299  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10304  0.0  0.0  0.0  1.0  0.0  0.0  0.0
x10305  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[1503 rows x 7 columns],           0    1    2    3    4    5    6
x15     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x22     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x23     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x48     0.0  0.0  0.0  0.0  1.0  0.0  0.0
x55     0.0  0.0  0.0  0.0  1.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10284  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10295  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10298  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10302  0.0  0.0  0.0  0.0  1.0  0.0  0.0
x10310  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[1470 rows x 7 columns],           0    1    2    3    4    5    6
x2      0.0  0.0  0.0  0.0  0.0  1.0  0.0
x3      0.0  0.0  0.0  0.0  0.0  1.0  0.0
x6      0.0  0.0  0.0  0.0  0.0  1.0  0.0
x7      0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10     0.0  0.0  0.0  0.0  0.0  1.0  0.0
...     ...  ...  ...  ...  ...  ...  ...
x10282  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10292  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10303  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10307  0.0  0.0  0.0  0.0  0.0  1.0  0.0
x10308  0.0  0.0  0.0  0.0  0.0  1.0  0.0

[1604 rows x 7 columns],           0    1    2    3    4    5    6
x4      0.0  0.0  0.0  0.0  0.0  0.0  1.0
x13     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x33     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x44     0.0  0.0  0.0  0.0  0.0  0.0  1.0
x56     0.0  0.0  0.0  0.0  0.0  0.0  1.0
...     ...  ...  ...  ...  ...  ...  ...
x10273  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10274  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10289  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10291  0.0  0.0  0.0  0.0  0.0  0.0  1.0
x10309  0.0  0.0  0.0  0.0  0.0  0.0  1.0

[1523 rows x 7 columns]]

 Cluster 1:

Linear Regression:
(1145, 919) (1145,)
(382, 919) (382,)
Score: 5.793432710847932e+21

Decission Tree:
(1145, 919) (1145,)
(382, 919) (382,)
Score: 99.22386184420812


 Cluster 2:

Linear Regression:
(998, 919) (998,)
(333, 919) (333,)
Score: 2.008279492791938e+22

Decission Tree:
(998, 919) (998,)
(333, 919) (333,)
Score: 94.35406751195947


 Cluster 3:

Linear Regression:
(1014, 919) (1014,)
(338, 919) (338,)
Score: 1.2743163844301404e+22

Decission Tree:
(1014, 919) (1014,)
(338, 919) (338,)
Score: 155.1643927120118


 Cluster 4:

Linear Regression:
(1127, 919) (1127,)
(376, 919) (376,)
Score: 2.1096386364134186e+22

Decission Tree:
(1127, 919) (1127,)
(376, 919) (376,)
Score: 103.92812421260638


 Cluster 5:

Linear Regression:
(1102, 919) (1102,)
(368, 919) (368,)
Score: 8.968071974148814e+21

Decission Tree:
(1102, 919) (1102,)
(368, 919) (368,)
Score: 98.25820902611413


 Cluster 6:

Linear Regression:
(1203, 919) (1203,)
(401, 919) (401,)
Score: 7.4191662503068275e+22

Decission Tree:
(1203, 919) (1203,)
(401, 919) (401,)
Score: 156.6568146220449


 Cluster 7:

Linear Regression:
(1142, 919) (1142,)
(381, 919) (381,)
Score: 3.3459742682146532e+22

Decission Tree:
(1142, 919) (1142,)
(381, 919) (381,)
Score: 89.17818723599738

## Model Output

In [71]:
trainModel(param6, df_pat, 6)

 Cluster 1:

Linear Regression:
(1371, 919) (1371,)
(458, 919) (458,)
Score: 6.828954921385209e+21

Decission Tree:
(1371, 919) (1371,)
(458, 919) (458,)
Score: 137.43996353296941


 Cluster 2:

Linear Regression:
(1236, 919) (1236,)
(412, 919) (412,)
Score: 3.103660972183598e+20

Decission Tree:
(1236, 919) (1236,)
(412, 919) (412,)
Score: 83.7332407196238


 Cluster 3:

Linear Regression:
(1248, 919) (1248,)
(417, 919) (417,)
Score: 6.634104343517731e+23

Decission Tree:
(1248, 919) (1248,)
(417, 919) (417,)
Score: 78.98660366091129


 Cluster 4:

Linear Regression:
(1278, 919) (1278,)
(426, 919) (426,)
Score: 9.465720133708987e+22

Decission Tree:
(1278, 919) (1278,)
(426, 919) (426,)
Score: 74.84412773136151


 Cluster 5:

Linear Regression:
(1259, 919) (1259,)
(420, 919) (420,)
Score: 2.32571737119041e+21

Decission Tree:
(1259, 919) (1259,)
(420, 919) (420,)
Score: 133.4399845166905


 Cluster 6:

Linear Regression:
(1338, 919) (1338,)
(447, 919) (447,)
Score: 3.9776383025909194e+23

Decission Tree:
(1338, 919) (1338,)
(447, 919) (447,)
Score: 165.59670129794185

In [72]:
trainModel(param6, df_pat, 6)

 Cluster 1:

Linear Regression:
(1371, 919) (1371,)
(458, 919) (458,)
Score: 5.105148188629968e+21

Decission Tree:
(1371, 919) (1371,)
(458, 919) (458,)
Score: 106.89187750148473


 Cluster 2:

Linear Regression:
(1236, 919) (1236,)
(412, 919) (412,)
Score: 6.481093610051739e+22

Decission Tree:
(1236, 919) (1236,)
(412, 919) (412,)
Score: 60.36771204453883


 Cluster 3:

Linear Regression:
(1248, 919) (1248,)
(417, 919) (417,)
Score: 5.463524672406002e+22

Decission Tree:
(1248, 919) (1248,)
(417, 919) (417,)
Score: 77.32249015280576


 Cluster 4:

Linear Regression:
(1278, 919) (1278,)
(426, 919) (426,)
Score: 1.17325314465331e+23

Decission Tree:
(1278, 919) (1278,)
(426, 919) (426,)
Score: 91.26377260199531


 Cluster 5:

Linear Regression:
(1259, 919) (1259,)
(420, 919) (420,)
Score: 1.7854001164092706e+20

Decission Tree:
(1259, 919) (1259,)
(420, 919) (420,)
Score: 74.1483627472619


 Cluster 6:

Linear Regression:
(1338, 919) (1338,)
(447, 919) (447,)
Score: 5.565527277315093e+23

Decission Tree:
(1338, 919) (1338,)
(447, 919) (447,)
Score: 134.40663541333333

In [27]:
trainModel(param7, df_pat, 7)

 Cluster 1:

Linear Regression:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 2.8145374505413915e+23

Decission Tree:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 115.31490418115071


 Cluster 2:

Linear Regression:
(1136, 919) (1136,)
(379, 919) (379,)
Score: 8.454886024675326e+22

Decission Tree:
(1136, 919) (1136,)
(379, 919) (379,)
Score: 91.89228517860819


 Cluster 3:

Linear Regression:
(1071, 919) (1071,)
(357, 919) (357,)
Score: 1.4067802554487315e+21

Decission Tree:
(1071, 919) (1071,)
(357, 919) (357,)
Score: 166.63354083523805


 Cluster 4:

Linear Regression:
(1095, 919) (1095,)
(366, 919) (366,)
Score: 4.475922326244784e+22

Decission Tree:
(1095, 919) (1095,)
(366, 919) (366,)
Score: 100.42605573841531


 Cluster 5:

Linear Regression:
(1131, 919) (1131,)
(378, 919) (378,)
Score: 3.729068224822945e+21

Decission Tree:
(1131, 919) (1131,)
(378, 919) (378,)
Score: 96.36107039550265


 Cluster 6:

Linear Regression:
(1097, 919) (1097,)
(366, 919) (366,)
Score: 7.56854372842694e+22

Decission Tree:
(1097, 919) (1097,)
(366, 919) (366,)
Score: 161.37499989598362


 Cluster 7:

Linear Regression:
(1107, 919) (1107,)
(370, 919) (370,)
Score: 2.4185486797949192e+22

Decission Tree:
(1107, 919) (1107,)
(370, 919) (370,)
Score: 126.58702053743242

In [74]:
trainModel(param100_7, df_pat, 7)

 Cluster 1:

Linear Regression:
(1275, 919) (1275,)
(426, 919) (426,)
Score: 9.599924462046514e+22

Decission Tree:
(1275, 919) (1275,)
(426, 919) (426,)
Score: 76.20507517715961


 Cluster 2:

Linear Regression:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 1.0311859342926146e+21

Decission Tree:
(1092, 919) (1092,)
(365, 919) (365,)
Score: 54.55866417457535


 Cluster 3:

Linear Regression:
(1026, 919) (1026,)
(342, 919) (342,)
Score: 1.802659239418777e+23

Decission Tree:
(1026, 919) (1026,)
(342, 919) (342,)
Score: 99.30641366163742


 Cluster 4:

Linear Regression:
(1064, 919) (1064,)
(355, 919) (355,)
Score: 2.4075310357751645e+23

Decission Tree:
(1064, 919) (1064,)
(355, 919) (355,)
Score: 121.01817180949297


 Cluster 5:

Linear Regression:
(1155, 919) (1155,)
(386, 919) (386,)
Score: 7.623448887043581e+23

Decission Tree:
(1155, 919) (1155,)
(386, 919) (386,)
Score: 147.41978776310881


 Cluster 6:

Linear Regression:
(1101, 919) (1101,)
(368, 919) (368,)
Score: 3.260249835175852e+25

Decission Tree:
(1101, 919) (1101,)
(368, 919) (368,)
Score: 134.33042929970108


 Cluster 7:

Linear Regression:
(1016, 919) (1016,)
(339, 919) (339,)
Score: 5.851599635427776e+20

Decission Tree:
(1016, 919) (1016,)
(339, 919) (339,)
Score: 96.53717679876843

In [28]:
trainModel(hinge7, df_pat, 7)

 Cluster 1:

Linear Regression:
(1145, 919) (1145,)
(382, 919) (382,)
Score: 1.8638545928207235e+23

Decission Tree:
(1145, 919) (1145,)
(382, 919) (382,)
Score: 106.06810051761781


 Cluster 2:

Linear Regression:
(998, 919) (998,)
(333, 919) (333,)
Score: 1.3241016060657095e+22

Decission Tree:
(998, 919) (998,)
(333, 919) (333,)
Score: 73.48950273582582


 Cluster 3:

Linear Regression:
(1014, 919) (1014,)
(338, 919) (338,)
Score: 8.294432485497003e+21

Decission Tree:
(1014, 919) (1014,)
(338, 919) (338,)
Score: 143.57824089189347


 Cluster 4:

Linear Regression:
(1127, 919) (1127,)
(376, 919) (376,)
Score: 9.516398568217709e+22

Decission Tree:
(1127, 919) (1127,)
(376, 919) (376,)
Score: 137.92262102579787


 Cluster 5:

Linear Regression:
(1102, 919) (1102,)
(368, 919) (368,)
Score: 3.9028995676274296e+23

Decission Tree:
(1102, 919) (1102,)
(368, 919) (368,)
Score: 108.36140588358695


 Cluster 6:

Linear Regression:
(1203, 919) (1203,)
(401, 919) (401,)
Score: 5.692965535458329e+17

Decission Tree:
(1203, 919) (1203,)
(401, 919) (401,)
Score: 156.5649859566334


 Cluster 7:

Linear Regression:
(1142, 919) (1142,)
(381, 919) (381,)
Score: 5.274501375891071e+23

Decission Tree:
(1142, 919) (1142,)
(381, 919) (381,)
Score: 118.46395791606301

In [29]:
trainModel(hinge20, df_pat, 20)

NameError: name 'hinge20' is not defined

In [30]:
trainModel(hinge10, df_pat, 10)

 Cluster 1:

Linear Regression:
(728, 919) (728,)
(243, 919) (243,)
Score: 1.547640555943283e+23

Decission Tree:
(728, 919) (728,)
(243, 919) (243,)
Score: 123.37350409773661


 Cluster 2:

Linear Regression:
(756, 919) (756,)
(252, 919) (252,)
Score: 4.858488139807545e+22

Decission Tree:
(756, 919) (756,)
(252, 919) (252,)
Score: 111.49082908115079


 Cluster 3:

Linear Regression:
(725, 919) (725,)
(242, 919) (242,)
Score: 1.7823168930889417e+23

Decission Tree:
(725, 919) (725,)
(242, 919) (242,)
Score: 92.0645657770248


 Cluster 4:

Linear Regression:
(785, 919) (785,)
(262, 919) (262,)
Score: 3.7093980363677898e+22

Decission Tree:
(785, 919) (785,)
(262, 919) (262,)
Score: 174.61384428030533


 Cluster 5:

Linear Regression:
(769, 919) (769,)
(257, 919) (257,)
Score: 3.5866619933918457e+22

Decission Tree:
(769, 919) (769,)
(257, 919) (257,)
Score: 89.39794778447471


 Cluster 6:

Linear Regression:
(739, 919) (739,)
(247, 919) (247,)
Score: 5.029653779660483e+21

Decission Tree:
(739, 919) (739,)
(247, 919) (247,)
Score: 110.356764152834


 Cluster 7:

Linear Regression:
(852, 919) (852,)
(285, 919) (285,)
Score: 5.9721072549627555e+22

Decission Tree:
(852, 919) (852,)
(285, 919) (285,)
Score: 98.50009546470176


 Cluster 8:

Linear Regression:
(795, 919) (795,)
(266, 919) (266,)
Score: 1.164658800351417e+21

Decission Tree:
(795, 919) (795,)
(266, 919) (266,)
Score: 99.46892487597744


 Cluster 9:

Linear Regression:
(787, 919) (787,)
(263, 919) (263,)
Score: 2.4223190620972978e+23

Decission Tree:
(787, 919) (787,)
(263, 919) (263,)
Score: 111.84887501657796


 Cluster 10:

Linear Regression:
(792, 919) (792,)
(265, 919) (265,)
Score: 1.919230537192631e+23

Decission Tree:
(792, 919) (792,)
(265, 919) (265,)
Score: 51.96701413490566

In [31]:
trainModel(origin20, df_pat, 20)

 Cluster 1:

Linear Regression:
(2, 919) (2,)
(1, 919) (1,)
Score: 0.6404185299408283

Decission Tree:
(2, 919) (2,)
(1, 919) (1,)
Score: 1.3064489999999995


 Cluster 2:

Linear Regression:
(844, 919) (844,)
(282, 919) (282,)
Score: 2.771791993502745e+21

Decission Tree:
(844, 919) (844,)
(282, 919) (282,)
Score: 8.233064853829788


 Cluster 3:

Linear Regression:
(2, 919) (2,)
(1, 919) (1,)
Score: 76.62680296963988

Decission Tree:
(2, 919) (2,)
(1, 919) (1,)
Score: 137.82760000000002


 Cluster 4:

Linear Regression:
(1214, 919) (1214,)
(405, 919) (405,)
Score: 1.2931379920447186e+21

Decission Tree:
(1214, 919) (1214,)
(405, 919) (405,)
Score: 423.1826870244259


 Cluster 5:

Linear Regression:
(76, 919) (76,)
(26, 919) (26,)
Score: 121.13836947259418

Decission Tree:
(76, 919) (76,)
(26, 919) (26,)
Score: 98.10329950576923


 Cluster 6:

Linear Regression:
(75, 919) (75,)
(26, 919) (26,)
Score: 25.63677034884739

Decission Tree:
(75, 919) (75,)
(26, 919) (26,)
Score: 50.7272253673077

Cluster7 is empty.


 Cluster 8:

Linear Regression:
(26, 919) (26,)
(9, 919) (9,)
Score: 0.7304843680754701

Decission Tree:
(26, 919) (26,)
(9, 919) (9,)
Score: 1.4921775777777777


 Cluster 9:

Linear Regression:
(1749, 919) (1749,)
(584, 919) (584,)
Score: 3.329131864611476e+23

Decission Tree:
(1749, 919) (1749,)
(584, 919) (584,)
Score: 68.65922500875428


 Cluster 10:

Linear Regression:
(3, 919) (3,)
(2, 919) (2,)
Score: 89.81328251733834

Decission Tree:
(3, 919) (3,)
(2, 919) (2,)
Score: 121.04543125


 Cluster 11:

Linear Regression:
(378, 919) (378,)
(126, 919) (126,)
Score: 3.176829724143634e+20

Decission Tree:
(378, 919) (378,)
(126, 919) (126,)
Score: 16.91592469373016


 Cluster 12:

Linear Regression:
(1068, 919) (1068,)
(357, 919) (357,)
Score: 1.1870555673031614e+20

Decission Tree:
(1068, 919) (1068,)
(357, 919) (357,)
Score: 9.82018753837535


 Cluster 13:

Linear Regression:
(3, 919) (3,)
(2, 919) (2,)
Score: 6.901392326015787

Decission Tree:
(3, 919) (3,)
(2, 919) (2,)
Score: 0.21662513000000005


 Cluster 14:

Linear Regression:
(1644, 919) (1644,)
(548, 919) (548,)
Score: 5.041855443727194e+21

Decission Tree:
(1644, 919) (1644,)
(548, 919) (548,)
Score: 13.746080879192517


 Cluster 15:

Linear Regression:
(15, 919) (15,)
(5, 919) (5,)
Score: 31.441384309780567

Decission Tree:
(15, 919) (15,)
(5, 919) (5,)
Score: 67.27522798600002


 Cluster 16:

Linear Regression:
(55, 919) (55,)
(19, 919) (19,)
Score: 0.4976396704215155

Decission Tree:
(55, 919) (55,)
(19, 919) (19,)
Score: 0.3814458486842105


 Cluster 17:

Linear Regression:
(260, 919) (260,)
(87, 919) (87,)
Score: 1250927848718897.2

Decission Tree:
(260, 919) (260,)
(87, 919) (87,)
Score: 6.4858199872413795

Cluster18 is empty.


 Cluster 19:

Linear Regression:
(312, 919) (312,)
(104, 919) (104,)
Score: 217.08238400363965

Decission Tree:
(312, 919) (312,)
(104, 919) (104,)
Score: 6.914782061153847

Cluster20 is empty.

In [ ]:
trainModel(origin5, df_pat, 5)